<a href="https://colab.research.google.com/github/born99/video_summarize_dsf/blob/master/Copy_of_Demo7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive 
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
!pwd
import os
os.chdir('/content/drive/My Drive/video_summarize_dsf')

!pip install chainer
!pip install torch
!pip install scikit-video
!pip install cupy-cuda111

/content


In [3]:
import numpy as np
import os
import json

from func.nets import vid_enc, vid_enc_vgg19
from chainer import serializers

import sys
sys.path.append('script/')
from summarize import get_flabel
from func.sampling.vsum import VSUM

import chainer
from chainer import configuration

import torch

/usr/local/lib/python3.7/dist-packages/chainer/_environment_check.py:75: UserWarning: 
--------------------------------------------------------------------------------
CuPy (cupy-cuda111) version 9.4.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy-cuda111>=7.7.0,<8.0.0'

See the following page for more details:
  https://docs.cupy.dev/en/latest/install.html
--------------------------------------------------------------------------------

  requirement=requirement, help=help))


In [4]:
# settings
feat_type = 'smt_feat' # smt_feat (proposed) or vgg

# load embedding model
if feat_type == 'smt_feat':
    model = vid_enc.Model()
    print('model:', type(model))
    serializers.load_npz('data/trained_model/model_par', model)
    print('model:', type(model))
elif feat_type == 'vgg':
    model = vid_enc_vgg19.Model()
    print('model:', type(model))
else:
    raise RuntimeError('[invalid feat_type] use smt_feat or vgg')

model: <class 'func.nets.vid_enc.Model'>
model: <class 'func.nets.vid_enc.Model'>


In [5]:
# prepair output dir
d_name = 'summe'
dataset_root = 'data/{}/'.format(d_name)
out_dir = 'results/{:}/{:}/'.format(d_name, feat_type)
print('save to: ', out_dir)

if not os.path.exists(out_dir):
    os.makedirs(out_dir)

save to:  results/summe/smt_feat/


In [6]:
# load dataset metadata
dataset = json.load(open(dataset_root + 'dataset.json'))
video_id = [d['videoID'] for d in dataset]

print('Video list:')
for vi in video_id:
    print('-', vi)

Video list:
- Cooking


In [7]:
# summarize video
v_id = 'Cooking'

with configuration.using_config('train', False):
    with chainer.no_backprop_mode():
        vsum = VSUM(v_id, model, dataset=d_name, seg_l=5)

_, frames, _ = vsum.summarizeRep(seg_l=5, weights=[1.0, 0.0])

# get 0/1 label for each frame
fps = vsum.dataset.data['fps']
fnum = vsum.dataset.data['fnum']
label = get_flabel(frames, fnum, fps, seg_l=5)
print('label: ',label)

ロードした動画のID: Cooking
budget: 2
feat: <class 'numpy.ndarray'>
label:  [[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [8]:
!pwd
!python script/summarize.py
!python script/evaluate.py results/summe/smt_feat

/content/drive/MyDrive/video_summarize_dsf
INFO:numexpr.utils:NumExpr defaulting to 2 threads.
/usr/local/lib/python3.7/dist-packages/chainer/_environment_check.py:75: UserWarning: 
--------------------------------------------------------------------------------
CuPy (cupy-cuda111) version 9.4.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy-cuda111>=7.7.0,<8.0.0'

See the following page for more details:
  https://docs.cupy.dev/en/latest/install.html
--------------------------------------------------------------------------------

  requirement=requirement, help=help))
resultの保存先: results/summe/smt_feat/
ロードした動画のID: Cooking
budget: 2
feat: <class 'numpy.ndarray'>
frames:  [['000624.jpg', '000639.jpg', '000654.jpg', '000669.jpg', '000684.jpg'], ['001219.jpg', '001233.jpg', '001248.jpg', '001263.jpg', '001278.jpg']]
fps:  14.854001108852339
fnum:  1286
label:  2
res_base: results/summe/smt_feat/
v_id

In [9]:
# write summarized video
from skvideo.io import vread, vwrite

# video_path = 'video_summarize_dsf/data/summe/%s.webm' % v_id
video_path = 'data/summe/abc.mp4'

video_data = vread(video_path)
print('video_data', video_data)
video_data 
sum_vid = video_data[label.ravel().astype(bool), :,:,:]

print ('writing video to', 'sum_%s.mp4'%v_id)
vwrite('sum_%s.mp4'%v_id, sum_vid)

video_data [[[[120 113  88]
   [123 116  91]
   [122 114  87]
   ...
   [ 31  13  21]
   [ 35  13  14]
   [ 36  14  15]]

  [[123 116  91]
   [123 116  91]
   [122 114  87]
   ...
   [ 29  11  19]
   [ 33  11  12]
   [ 36  14  15]]

  [[124 117  93]
   [122 115  91]
   [123 114  90]
   ...
   [ 28  14  15]
   [ 30  14  11]
   [ 32  16  13]]

  ...

  [[ 66  65  56]
   [ 66  65  56]
   [ 68  67  58]
   ...
   [ 20  30  77]
   [ 22  31  84]
   [ 25  34  87]]

  [[ 65  65  51]
   [ 67  67  53]
   [ 69  69  55]
   ...
   [ 18  32  78]
   [ 16  31  80]
   [ 18  33  82]]

  [[ 65  65  51]
   [ 68  68  54]
   [ 69  69  55]
   ...
   [ 20  34  80]
   [ 17  32  81]
   [ 16  31  80]]]


 [[[139 108 109]
   [138 107 108]
   [137 111 108]
   ...
   [ 22  10   5]
   [ 20   9   1]
   [ 23  12   4]]

  [[139 108 109]
   [138 107 108]
   [137 111 108]
   ...
   [ 23  11   6]
   [ 22  11   3]
   [ 25  14   6]]

  [[136 110 107]
   [135 109 106]
   [134 113 106]
   ...
   [ 24  12  10]
   [ 24  14   9]


IndexError: ignored